import {
  masjid1_1, masjid1_2, masjid1_3, masjid1_4, masjid1_5,
  masjid2_1, masjid2_2, masjid2_3, masjid2_4, masjid2_5,
  masjid3_1, masjid3_2, masjid3_3, masjid3_4, masjid3_5,
  masjid4_1, masjid4_2, masjid4_3,
  masjid5_1, masjid5_2,
  masjid6_1, masjid6_2, masjid6_3, masjid6_4, masjid6_5,
  masjid7_1, masjid7_2, masjid7_3, masjid7_4, masjid7_5,
  masjid8_1, masjid8_2, masjid8_3, masjid8_4, masjid8_5,
  masjid9_1, masjid9_2, masjid9_3, masjid9_4, masjid9_5,
  masjid10_1, masjid10_2, masjid10_3, masjid10_4, masjid10_5,
  masjid11_1, masjid11_2, masjid11_3, masjid11_4, masjid11_5,
  masjid12_1, masjid12_2, masjid12_3, masjid12_4, masjid12_5,
  masjid13_1, masjid13_2, masjid13_3, masjid13_4, masjid13_5,
  masjid14_1, masjid14_2, masjid14_3, masjid14_4, masjid14_5,
  masjid15_1, masjid15_2, masjid15_3, masjid15_4, masjid15_5,
  masjid16_1, masjid16_2, masjid16_3, masjid16_4, masjid16_5,
} from "../assets";

export default {
  "features": [
    {
      "mosque": {
        "id": 1,
        "name": "Wihdatul Ummah",
        "latitude": -6.353292,
        "longitude": 106.777251,
        "address": "Jl. Bukit Barisan",
        "rating": 4.9,
        "reviews": 584,
        "info": "Jl. Bukit Barisan No.Blok J, RT.011/RW.014, Limo, Kec. Limo, Kota Depok, Jawa Barat 16514",
        "thumbnail": masjid1_1,
        "images": [
          masjid1_1,
          masjid1_2,
          masjid1_3,
          masjid1_4,
          masjid1_5,
        ],
        "facilities": ["Mimbar", "Tv Informasi", "Kipas", "Mic", "AC", "CCTV", "Parkir Mobil", "Parkir Motor", "Ambulance", "Toilet", "Tempat Wudhu", "Akses Kursi Roda"]
      }
    },
    {
      "mosque": {
        "id": 2,
        "name": "Nurul Qalbi",
        "latitude": -6.36708,
        "longitude": 106.773323,
        "address": "Jl. H.Masdulhak",
        "rating": 5,
        "reviews": 25,
        "info": "Jl. .H.Masdulhak, Limo, Kec. Limo, Kota Depok, Jawa Barat 16515",
        "thumbnail": masjid2_1,
        "images": [
          masjid2_1,
          masjid2_2,
          masjid2_3,
          masjid2_4,
          masjid2_5,
        ],
        "facilities": ["Meja Belajar",
          "Air Minum",
          "Kipas",
          "Halaman Terbuka",
          "Papan Informasi",
          "Kotak Amal",
          "Tirai Pembatas Akhwat Dan Ikhwan",
          "Toilet",
          "Tempat Wudhu",
          "Rak Al Qur'an",
          "Speaker",
          "Papan Jam Digital",
          "AC",
        ]

      }
    },
    {
      "mosque": {
        "id": 3,
        "name": "Nahdatul Ummah",
        "latitude": -6.380997,
        "longitude": 106.781104,
        "address": "Jl. Kp. Grogol Sebrang",
        "rating": 4.3,
        "reviews": 11,
        "info": "Jl. Kp. Grogol Sebrang, RT.01/RW.06, Grogol, Kec. Limo, Kota Depok, Jawa Barat 16514",
        "thumbnail": masjid3_1,
        "images": [
          masjid3_1,
          masjid3_2,
          masjid3_3,
          masjid3_4,
          masjid3_5,
        ],
        "facilities": ["Rak Al Qur'an",
          "Rak Mukena Sarung",
          "Kursi Lipat",
          "Kotak Amal",
          "Parkir Motor",
          "Kipas",
          "Tirai Pembatas Akhwat Dan Ikhwan",
          "Mimbar",
          "Toa",
          "2 Lantai"]

      }
    },
    {
      "mosque": {
        "id": 4,
        "name": "Jami' Al Muthmainnah",
        "latitude": -6.382336,
        "longitude": 106.768899,
        "address": "Jl. Meruyung Raya",
        "rating": 4.8,
        "reviews": 193,
        "info": "Jl. Meruyung Raya, Meruyung, Kec. Limo, Kota Depok, Jawa Barat 16515",
        "thumbnail": masjid4_1,
        "images": [
          masjid4_1,
          masjid4_2,
          masjid4_3,
        ],
        "facilities": ["Mimbar",
          "Parkir Mobil Dan Motor",
          "Ambulance",
          "Kotak Amal",
          "Papan Informasi",
          "Toilet",
          "Tempat Wudhu",
          "Air Minum",
          "Kipas",
          "Tirai Pembatas",]

      }
    },
    {
      "mosque": {
        "id": 5,
        "name": "Jami' Al Maghfiroh",
        "latitude": -6.378611,
        "longitude": 106.769989,
        "address": "Jl. Ustadz Arifin Ilham",
        "rating": 4.6,
        "reviews": 100,
        "info": "Jl. Ustadz Arifin Ilham No.50, RT.4/RW.5, Meruyung, Kec. Limo, Kota Depok, Jawa Barat 16514",
        "thumbnail": masjid5_1,
        "images": [
          masjid5_1,
          masjid5_2,
        ],
        "facilities": ["Masih Dalam Tahap Pembangunan",]

      }
    },
    {
      "mosque": {
        "id": 6,
        "name": "Jami' Nuurul Hidayah",
        "latitude": -6.367213,
        "longitude": 106.782975,
        "address": "Jl. Pendowo",
        "rating": 4.7,
        "reviews": 161,
        "info": "JL. Pendowo, Kec. Limo, Kota Depok, Jawa Barat 16515",
        "thumbnail": masjid6_1,
        "images": [
          masjid6_1,
          masjid6_2,
          masjid6_3,
          masjid6_4,
          masjid6_5,
        ],
        "facilities": ["Hand Sanitizer",
          "Papan Informasi",
          "Kotak Amal",
          "Parkir Mobil Dan Motor",
          "Mimbar",
          "AC",
          "Papan Jam Digital",
          "Kipas",
          "Toilet",
          "Tempat Wudhu",
          "Rak Kitab",
          "Rak Mukena Sarung",
          "Toa",
          "Bedug",]

      }
    },
    {
      "mosque": {
        "id": 7,
        "name": "Jami' Nurul Hakim",
        "latitude": -6.373543,
        "longitude": 106.776794,
        "address": "Jl. Arthayasa",
        "rating": 4.9,
        "reviews": 69,
        "info": "Jl. Arthayasa No.89, Meruyung, Kec. Limo, Kota Depok, Jawa Barat 16515",
        "thumbnail": masjid7_1,
        "images": [
          masjid7_1,
          masjid7_2,
          masjid7_3,
          masjid7_4,
          masjid7_5,
        ],
        "facilities": ["Hand Sanitizer",
          "Kipas",
          "AC",
          "Tirai Pembatas",
          "Rak Kitab",
          "Rak Mukena",
          "Kursi Lipat",
          "Mimbar",
          "Gapura",
          "Kolam Ikan",
          "Ambulance",
          "Toilet",
          "Tempat Wudhu",]

      }
    },
    {
      "mosque": {
        "id": 8,
        "name": "Jami' Miftahul Jannah",
        "latitude": -6.381304,
        "longitude": 106.775742,
        "address": "Jl. Bina Warga Dalam",
        "rating": 4.7,
        "reviews": 29,
        "info": "Jl. Bina Warga Dalam, Meruyung, Limo, Meruyung, Depok, Kota Depok, Jawa Barat 16514",
        "thumbnail": masjid8_1,
        "images": [
          masjid8_1,
          masjid8_2,
          masjid8_3,
          masjid8_4,
          masjid8_5,
        ],
        "facilities": ["Kipas",
          "Halaman Terbuka",
          "Toa",
          "Air Minum",
          "Gelas",
          "Kamar Marbot",
          "Papan Informasi",
          "Meja",
          "Kursi",
          "Toilet",
          "Tempat Wudhu",
          "Parkir Mobil",
          "Mobil Motor",
          "AC",
          "Rak Kitab",
          "Rak Mukena",
          "Jam Digital",]

      }
    },
    {
      "mosque": {
        "id": 9,
        "name": "Jami' Al Muttaqien",
        "latitude": -6.382837,
        "longitude": 106.781138,
        "address": "Jl. Kp. Grogol Sebrang",
        "rating": 4.5,
        "reviews": 10,
        "info": "Jl. Kp. Grogol Sebrang No.14, Grogol, Kec. Limo, Kota Depok, Jawa Barat 16514",
        "thumbnail": masjid9_1,
        "images": [
          masjid9_1,
          masjid9_2,
          masjid9_3,
          masjid9_4,
          masjid9_5,
        ],
        "facilities": ["Parkir Mobil Motor",
          "Rak Kitab",
          "Rak Mukena",
          "Tirai Pembatas",
          "Papan Pengumuman",
          "Tempat Wudhu",
          "Toilet",
          "Kipas",
          "AC",
          "Jam Digital",
          "Speaker",
          "Mimbar",]

      }
    },
    {
      "mosque": {
        "id": 10,
        "name": "Jami' Al Mu'izzu",
        "latitude": -6.376196,
        "longitude": 106.776903,
        "address": "Jl. Perumahan Lemigas",
        "rating": 4.3,
        "reviews": 16,
        "info": "Jl. Perumahan Lemigas No.Rt 002/009, Meruyung, Kec. Limo, Kota Depok, Jawa Barat 16515",
        "thumbnail": masjid10_1,
        "images": [
          masjid10_1,
          masjid10_2,
          masjid10_3,
          masjid10_4,
          masjid10_5,
        ],
        "facilities": ["AC",
          "Kursi Lipat",
          "Mimbar",
          "Jam Digital",
          "Speaker",
          "Kotak Amal",
          "Halaman Terbuka",
          "Papan Tulis",
          "Kipas",
          "Kursi Kecil",
          "Rak Kitab",
          "Rak Mukena",
          "Toilet",
          "Tempat Wudhu",
          "Parkir Motor",]
      }
    },
    {
      "mosque": {
        "id": 11,
        "name": "Az Zahra",
        "latitude": -6.381717,
        "longitude": 106.779303,
        "address": "Jl. Komp. De Fatmawati",
        "rating": 5.0,
        "reviews": 2,
        "info": "Jl. Komp. De Fatmawati, Meruyung, Kec. Limo, Kota Depok, Jawa Barat 16514",
        "thumbnail": masjid11_1,
        "images": [
          masjid11_1,
          masjid11_2,
          masjid11_3,
          masjid11_4,
          masjid11_5,
        ],
        "facilities": ["Mimbar",
          "Jam Digital",
          "Kipas",
          "Mic",
          "Stand Mic",
          "AC",
          "Tirai Pembatas",
          "Speaker",
          "Papan Tulis",
          "Halaman Terbuka",
          "Rak Kitab",
          "Bedug",
          "Tempat Wudhu",
          "Toilet",]

      }
    },
    {
      "mosque": {
        "id": 12,
        "name": "As Sunnah",
        "latitude": -6.379376,
        "longitude": 106.773367,
        "address": "Jl. Tiga Putra",
        "rating": 4.9,
        "reviews": 252,
        "info": "Jl. Tiga Putra No.RT 01/011, Meruyung, Kec. Limo, Kota Depok, Jawa Barat 16532",
        "thumbnail": masjid12_1,
        "images": [
          masjid12_1,
          masjid12_2,
          masjid12_3,
          masjid12_4,
          masjid12_5,
        ],
        "facilities": ["Kipas",
          "Cctv",
          "Tirai Pembatas",
          "Kotak Amal",
          "Meja Lipat",
          "Rak Kitab",
          "AC",
          "Tv",
          "Mimbar",
          "Mic",
          "Jam Digital",
          "Speaker",
          "Toilet",
          "Tempat Wudhu",
          "Rak Sepatu",
          "Papan Informasi",
          "Ambulance",]
      }
    },
    {
      "mosque": {
        "id": 13,
        "name": "Ar Rahman",
        "latitude": -6.373917,
        "longitude": 106.782062,
        "address": "Jl. Swadaya",
        "rating": 5.0,
        "reviews": 21,
        "info": "Jl. Swadaya No.81 Kampung, Jl. Raya Pulo Mangga, Grogol, Kec. Limo, Kota Depok, Jawa Barat 16514",
        "thumbnail": masjid13_1,
        "images": [
          masjid13_1,
          masjid13_2,
          masjid13_3,
          masjid13_4,
          masjid13_5,
        ],
        "facilities": ["Kipas",
          "Speaker",
          "Halaman Terbuka",
          "Papan Informasi",
          "Jam Digital",
          "Mimbar",
          "AC",
          "Kotak Amal",
          "Tempat Wudhu",
          "Toilet",
          "Taman",
          "Cermin",
          "Toa",]

      }
    },
    {
      "mosque": {
        "id": 14,
        "name": "Al Muttaqien",
        "latitude": -6.360533,
        "longitude": 106.776425,
        "address": "Jl. Kp. Grogol Sebrang",
        "rating": 4.8,
        "reviews": 465,
        "info": "Jl. Naman Iskandar No.1, Limo, Kec. Limo, Kota Depok, Jawa Barat 16514",
        "thumbnail": masjid14_1,
        "images": [
          masjid14_1,
          masjid14_2,
          masjid14_3,
          masjid14_4,
          masjid14_5,
        ],
        "facilities": ["Mimbar",
          "Mic",
          "Kipas",
          "AC",
          "Speaker",
          "Jam Digital",
          "Tempat Wudhu",
          "Toilet",
          "Papan Pengumuman",
          "Tirai Pembatas",
          "Rak Kitab",
          "Rak Mukena",
          "Parkiran",]

      }
    },
    {
      "mosque": {
        "id": 15,
        "name": "Al Mujahidin",
        "latitude": -6.375073,
        "longitude": 106.771082,
        "address": "Jl. Al-Mujahidin",
        "rating": 4.7,
        "reviews": 136,
        "info": "Jl. Al-Mujahidin No.77, Meruyung, Kec. Limo, Kota Depok, Jawa Barat 16514",
        "thumbnail": masjid15_1,
        "images": [
          masjid15_1,
          masjid15_2,
          masjid15_3,
          masjid15_4,
          masjid15_5,
        ],
        "facilities": ["Kipas",
          "Tirai Pembatas",
          "Rak Sepatu",
          "Speaker",
          "Jam Digital",
          "Mimbar",
          "Mic",
          "Cctv",
          "Toilet",
          "Tempat Wudhu",
          "Ambulance",]

      }
    },
    {
      "mosque": {
        "id": 16,
        "name": "Al Furqon",
        "latitude": -6.382589,
        "longitude": 106.768742,
        "address": "Jl. Al-Furqon",
        "rating": 5.0,
        "reviews": 2,
        "info": "Jl. Al-Furqon, Meruyung, Kec. Limo, Kota Depok, Jawa Barat 16515",
        "thumbnail": masjid16_1,
        "images": [
          masjid16_1,
          masjid16_2,
          masjid16_3,
          masjid16_4,
          masjid16_5,
        ],
        "facilities": ["Tempat Parkir",
          "Toa",
          "Tirai Pembatas",
          "Kipas",
          "Toilet",
          "Tempat Wudhu",
          "Mimbar",
          "Jam Digital",
          "Speaker",]

      }
    },
  ]
}